In [1]:
#import modules
import tensorflow as tf

# Check if eager execution allowed
tf.executing_eagerly() 

True

In [2]:
# Verify the tensorflow version 
print(tf.__version__)

2.0.0-dev20190312


In [3]:
# Create two random tensor matrices and add them
a = tf.random.normal((3, 3))

b = tf.random.normal((3, 3))
c = tf.add(a,b)
print(c)

tf.Tensor(
[[-0.77991253  1.2106223  -2.752781  ]
 [ 0.16683841  2.6813033   2.5160966 ]
 [ 0.3640358  -1.6790565  -0.3637447 ]], shape=(3, 3), dtype=float32)


In [4]:
# Multiply two random tensor matrices
print(a*b)

tf.Tensor(
[[ 0.07461509  0.36540586  1.1067437 ]
 [-0.6112719   1.7184025   0.7911235 ]
 [-1.1533982   0.7034673   0.01439272]], shape=(3, 3), dtype=float32)
