In [1]:
#import modules
import tensorflow as tf

# Verify the tensorflow version 
print(tf.__version__)


1.7.1


In [2]:
# Check if eager execution allowed
tf.executing_eagerly() 

False

In [3]:
# Create two random tensor matrices and add them
a = tf.random.normal((3, 3))

b = tf.random.normal((3, 3))

c = tf.add(a,b)

with tf.Session() as sess:
    result = sess.run(c)
    print(result)

[[-0.8474333   0.7448774   2.4805427 ]
 [ 1.7149274   1.369987   -0.36666977]
 [-0.01707703 -1.2533426   0.81924933]]


In [4]:
# Multiply two random tensor matrices
with tf.Session() as sess:
    result = sess.run(a*b)
    print(result)

[[ 2.2996545  -0.5654764   0.5937689 ]
 [ 0.19906399  0.15346451  0.48401126]
 [-0.36904284 -0.6500323  -0.5577736 ]]
